### ISSUE TITLE
Install in subpath of domain

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/gotify_ynh#22]
It seems the doc provides everything needed to NOT need a dedicated domain : 
https://gotify.net/docs/nginx
"At a subpath"

Could it be implemented ? :)

**Comment by plopoyop** [comment]
Last time I checked, it did not work. I don't remember, I think a problem with the websocket.
I may try again :)

**Comment by Salamandar** [comment]
Ok :)

**Comment by plopoyop** [comment]
done in https://github.com/YunoHost-Apps/gotify_ynh/pull/31
