### ISSUE TITLE
Add rewrite-proxy

### ISSUE THREAD

**Issue by linuxissuper** [YunoHost-Apps/gotify_ynh#33]
Thanks for gotify_ynh     
but would it be possible to also add the rewrite-proxy config?   
https://unifiedpush.org/users/distributors/gotify/#self-hosting    
    
I had to add this config else schildichat and fluffychat did not work

**Comment by supermamie** [comment]
I forced the upgrade to finally have this and it works perfectly !
But can you upgrade the version number so the upgrade is available without `-F` ?
