### ISSUE TITLE
unable to login after fresh install

### ISSUE THREAD

**Issue by jodumont** [YunoHost-Apps/gotify_ynh#5]
Hi;

### Login Failed
I tried three times
1 time with a stronger password, second time with an only alphanumeric password and the last time with a basic 24 characters password; but the login always failed.

### I also tried:
admin with admin
myusername@mydomain.tld with mypassword
myusername with mypassword

with firefox and chrome in normal and incognito mode

#### in the config.yml

The password generated with my keepassxc and the one declared in `/opt/yunohost/gotify/config.yml` are the same

#### in the gotify mysql db

the declared user is the one I choose during the installation, his `id` is 1 and the field `admin` indicate 1

I reenter my password via mysql and I still unable to login

### How I proceed 

1. declare my subdomain
2. configure the subdomain for the apps in yunohost
3. generate a let's encrypt certificate for the subdomain
4. install the apps via the "apps store"

## Error Logs

2019/05/28 09:34:30 [error] 16902#16902: *2200 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.150.123, server: push.glibre.net, request: "GET /static/css/main.99a0ea00.css HTTP/1.1", upstream: "http://[::1]:8080/static/css/main.99a0ea00.css", host: "push.glibre.net", referrer: "https://push.glibre.net/"
2019/05/28 09:35:28 [error] 16902#16902: *2226 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.150.45, server: push.glibre.net, request: "GET /admin HTTP/1.1", upstream: "http://[::1]:8080/admin", host: "push.glibre.net"
2019/05/28 09:35:55 [error] 16902#16902: *2238 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.150.45, server: push.glibre.net, request: "POST /client HTTP/1.1", upstream: "http://[::1]:8080/client", host: "push.glibre.net", referrer: "https://push.glibre.net/"
2019/05/28 09:43:07 [error] 16905#16905: *2317 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.150.45, server: push.glibre.net, request: "POST /client HTTP/1.1", upstream: "http://[::1]:8080/client", host: "push.glibre.net", referrer: "https://push.glibre.net/"
2019/05/28 09:45:05 [error] 19250#19250: *2385 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.150.45, server: push.glibre.net, request: "GET /version HTTP/1.1", upstream: "http://[::1]:8080/version", host: "push.glibre.net", referrer: "https://push.glibre.net/"
2019/05/28 12:43:05 [error] 23615#23615: *3010 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.150.93, server: push.glibre.net, request: "GET /version HTTP/1.1", upstream: "http://[::1]:8080/version", host: "push.glibre.net", referrer: "https://push.glibre.net/"

### PS: I don't have IPv6

# Does someones see my error and/or had this situation before ?

**Comment by plopoyop** [comment]
Hi,
In file `/etc/nginx/conf.d/push.glibre.net.d/gotify.conf` can you try to replace `http://localhost:8080/ ` by `http://127.0.0.1:8080`

If it's working, I'll change it in the package

**Comment by jodumont** [comment]
yes!
by using `127.0.0.1:8080` in **nginx** it's working
but also; if you replace **listenaddr**:127.0.0.1 in `/opt/yunohost/gotify/config.yml` by:
> listenaddr: localhost

**Comment by aslmx** [comment]
Somehow this is either broken again or not fixed. I have the exact same behaviour.

I checekd the nginx config, it seems okay.
I checked with both

listenaddr: localhost
and
127.0.0.1

... no luck.

i also just realized that even my user and pw are there plain text - and correct ;)

Any idea?
