### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/gotify_ynh#9]
Hi,

this is similar to #5 but my config files already have `127.0.0.1` instead of localhost set.

I get a 401 response to the POST request. How can I debug that?

Thanks in advance for your help, and for your work on this package!

**Comment by nicofrand** [comment]
I also tried restarting the service, did not help

**Comment by plopoyop** [comment]
Hi,
I don't see any debug logs.
You can check access logs using the command : `journalctl -xefu gotify`
I am not sure it is going to help.
You can check there is no typo for your username / password into the config file : `/opt/yunohost/gotify/config.yml`
Remember, the application is not using ynh SSO.

**Comment by nicofrand** [comment]
Thanks!

Here is what I found from `journalctl -xefu gotify`, I am afraid it is not helping much.
```
Mar 29 11:42:40 nicofrand.eu gotify-linux-amd64[25463]: [GIN] 2020/03/29 - 11:42:40 | 401 |  504.828088ms |       127.0.0.1 | POST     /client
Mar 29 11:42:40 nicofrand.eu gotify-linux-amd64[25463]: Error #01: you need to provide a valid access token or user credentials to access this api
```

I checked `/opt/yunohost/gotify/config.yml` and my credentials are correct indeed.
I checked the POST request in Firefox, nothing is sent in parameters so I guess the `Authorization` header is bearing the credentials but I don't know how to check that. Its value is `Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`.

**Comment by nicofrand** [comment]
OK, I tried adding this token directly in the nginx config like this:

```nginx
proxy_set_header Authorization "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
```

and it works, so it comes from the nginx config as far as I can say. I'll try and find why the header is not passed correctly.

**Comment by nicofrand** [comment]
I tried logging the $http_authorization variable by sending it back through `add_header                  X-debug $http_authorization always;` and it is not the same as the one sent:

![image](https://user-images.githubusercontent.com/3419050/77846638-ba7e1380-71b7-11ea-8b4e-147257d5fdab.png)

**Comment by plopoyop** [comment]
The POST request contains the client name as data and basic auth headers 
In firefox I right clicked on the request and copy as cURL :
```
curl 'https://gotify.domain.tld/client' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Content-Type: application/json;charset=utf-8' -H 'Authorization: Basic TOKEN' -H 'Origin: https://gotify.domain.tld' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://gotify.domain.tld/' -H 'TE: Trailers' --data '{"name":"firefox 74.0.0"}'

```

**Comment by plopoyop** [comment]
any error in firefox console ?

**Comment by nicofrand** [comment]
No, nothing in Firefox.
I believe the issue is in the nginx config since it works if I set the token in hard in it.

**Comment by nicofrand** [comment]
Got it, I'll open a MR.
